### ISSUE TITLE
一起搞起来

### ISSUE THREAD

**Issue by mishengqiang** [zhaotoday/yarnpkg-cn#1]
加入翻译

**Comment by xcatliu** [comment]
@zhaotoday @yanyu0517 @mishengqiang 
我看到官网支持多语言，所以想翻译好之后直接提 pr 就可以了，我已经提了一个 issue，大家一起来吧！

Issue: yarnpkg/website#176
Forked repo: https://github.com/xcatliu/yarnpkg.cn
Demo website: http://yarnpkg.cn/zh-Hans/

**Comment by mishengqiang** [comment]
@xcatliu 我转过去

**Comment by lifesign** [comment]
官方好像是想用 CrowdIn 翻译

**Comment by xcatliu** [comment]
@lifesign 嗯，感谢提醒，我看到了。我想看了文档顺手就翻译了吧，如果现在不接受 pr，翻译工作也不会白费。到时候再到 CrowdIn 上提交一次吧。

**Comment by zhaotoday** [comment]
目前我在翻译官网首页，近期上线到 yarnpkg.cn。

**Comment by xcatliu** [comment]
Hi, @zhaotoday 

现在 @yanyu0517 已经高效的把所有文档都翻译完了，并部署在了这个域名下： http://yarnpkg.top/

但是没有把源码提交到 GitHub，也无法让大家一起继续贡献翻译校对，也无法 merge 回官方仓库。

所以我和他有一次讨论，决定共同建设一个更加完善的仓库。
- 当时讨论的地址： https://github.com/yanyu0517/yarnpkgcn/issues/2
- 新的仓库（支持自动部署和 merge 回官方仓库）： https://github.com/xcatliu/cyarnpkg.com
- 新的域名： http://cyarnpkg.com/zh-Hans/
- 迁移进度： 大概为 30/65

如果你愿意的话，我们来一起建设这个仓库吧！

**Comment by zhaotoday** [comment]
@xcatliu 你好，目前我自己公司刚开始运营，精力较少，另外我个人能力也有限，会影响你们的进度。我后面会把你们的网址（ http://cyarnpkg.com/zh-Hans/ ）放到我网站（ http://www.yarnpkg.cn/ ）上。

**Comment by xcatliu** [comment]
@zhaotoday 创业不易，加油。

多个网址容易误导用户，不如我们统一成一个网址。我觉得你的域名最好，你看这样可不可行：
1. 你把 yarnpkg.cn 的域名 cname 指向 xcatliu.github.io
2. 我把配置搞好，让仓库的 gh-pages 分支的 cname 指向 yarnpkg.cn
3. 这样你就不用再重复的同步我的仓库（ https://github.com/xcatliu/yarnpkg.cn ）了
4. 我把你也加到仓库的管理员里面
5. 我把 cyarnpkg.com 直接指向 yarnpkg.cn
6. 等官方网站同意 merge 我们的翻译之后，我们把 cyarnpkg.com 和 yarnpkg.cn 都指向 yarnpkg.com/zh-Hans，避免同时维护两套翻译

**Comment by zhaotoday** [comment]
@xcatliu 好的，我已经把域名的 CNAME 指向 xcatliu.github.io。后期还有其他需要配合的，再找我。

**Comment by xcatliu** [comment]
@zhaotoday 已完成前五步。

感谢你提供的域名！

现在已经可以正常访问了： http://yarnpkg.cn/zh-Hans/

**Comment by lgh06** [comment]
默认是英语……？

**Comment by xcatliu** [comment]
@lgh06 默认语言还没有改过来，稍后改。
